# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  JoinFiles-benchmarks:
    dependencies:
    - base
    - JoinFiles
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Data
description: JoinFiles can join many files into one
executables:
  JoinFiles:
    dependencies:
    - base >= 4 && < 5
    - JoinFiles
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: yuhangwang/JoinFiles
library:
  dependencies:
  - base
  source-dirs: library
license: MIT
maintainer: Yuhang(Steven) Wang
name: JoinFiles
synopsis: Join many files into one
tests:
  JoinFiles-test-suite:
    dependencies:
    - base
    - JoinFiles
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.1.0'
